// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Samu_Sudents_Vs_Restapi.InterfaceData;

namespace WebApi_Samu_Sudents_Vs_Restapi.Migrations
{
    [DbContext(typeof(StudentDetailsContext))]
    partial class StudentDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_Samu_Sudents_Vs_Restapi.Models.StudentDetails", b =>
                {
                    b.Property<int>("studID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studAge")
                        .HasColumnType("int");

                    b.Property<string>("studName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studID");

                    b.ToTable("dbStudents");

                    b.HasData(
                        new
                        {
                            studID = 1,
                            StudAddress = "CTC",
                            studAge = 12,
                            studName = "Samu"
                        },
                        new
                        {
                            studID = 2,
                            StudAddress = "CTC1",
                            studAge = 15,
                            studName = "Samu1"
                        },
                        new
                        {
                            studID = 3,
                            StudAddress = "CTC2",
                            studAge = 16,
                            studName = "Samu2"
                        },
                        new
                        {
                            studID = 4,
                            StudAddress = "CTC3",
                            studAge = 19,
                            studName = "Samu3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
